# This workflow will build the Android project

name: Test Distribute

on:
  pull_request:
    branches: [ main ]
    types: [closed]
  workflow_dispatch:

jobs:
  build_and_distribute:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew and decrypt_secrets.sh
        run: |
          chmod +x gradlew
          chmod +x .github/encrypted_secrets/decrypt_secrets.sh
          pwd
      - name: Decrypt Secrets
        env:
          SECRETS_DECRYPT_PASSPHRASE: ${{ secrets.SECRETS_DECRYPT_PASSPHRASE }}
        run: .github/encrypted_secrets/decrypt_secrets.sh
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Add Release Notes
        env:
          TITLE: ${{github.event.pull_request.title}}
          BODY: ${{github.event.pull_request.body}}
        run: echo -e "${TITLE} \n${BODY}" > .github/RELEASE_NOTES.txt

      - name: Distribute with Firebase App Distribution
        run: ./gradlew appDistributionUploadDebug

